### PR TITLE
Convert types to and from `Value`s using serde

### LINKED ISSUE #79: Deserialize from `Dictionary`
Would be great to be able to deserialize a `Dictionary` into a struct. For example, in `serde_json` there's `serde_json::from_value()`.

### My use case
I have a plist with a bunch of dictionaries that I'd like to parse into enums of structs.
```rust
#[derive(Deserialize, Debug)]
#[serde(untagged)]
struct PlistFile {
  changes: Vec<Change>,
}

#[derive(Deserialize, Debug)]
#[serde(untagged)]
enum Change {
  Addition(Addition),
  // + other types I don't know about
}

#[derive(Deserialize, Debug)]
#[serde(deny_unknown_fields)]
struct Addition {
  example_field: String,
}
```

The problem is I don't know about all the possible variants of `Change`, so I need to figure that out. If I deserialize to the structs above, I get an unhelpful error message:
```
Unable to parse response: Serde("data did not match any variant of untagged enum Change")
```

So my plan was to instead deserialize to `Vec<Dictionary>`, then loop through the dicts and deserialize them individually - Then, if it fails, I can log the dict's fields to find out what I need to add.

### PR DESCRIPTION
**Pull request by ebarnard**
Closes #79.

### CODE REVIEW

File: src/de.rs [hunk 1]
```diff
@@ -424,3 +434,10 @@ pub fn from_reader_xml<R: Read, T: de::DeserializeOwned>(reader: R) -> Result<T,
     let mut de = Deserializer::new(reader);
     de::Deserialize::deserialize(&mut de)
 }
+
+/// Interprets a [`plist::Value`] as an instance of type `T`.
```
Comment (jcgruenhage) [inline src/de.rs:438]: `plist::Value` doesn't work with rustdoc here, because `plist` isn't in scope here. You can either use `Value` directly, or write `crate::Value`, or if you want the link to read `plist::Value`, you can do ``[`plist::Value`](Value)``

File: src/ser.rs [hunk 2]
```diff
@@ -802,3 +803,11 @@ pub fn to_writer_xml_with_options<W: Write, T: ser::Serialize>(
     let mut ser = Serializer::new(writer);
     value.serialize(&mut ser)
 }
+
+// Converts a `T` into a [`plist::Value`] which can represent any valid plist.
```
Comment (jcgruenhage) [inline src/ser.rs:807]: Same as above, with the additional problem that this is not a doc comment.

**Review by jcgruenhage — CHANGES_REQUESTED** [review]
Mostly looks good to me, except for a few small doc problems. A rebased version of this with the doc problems fixed is available at https://github.com/jcgruenhage/rust-plist/tree/serde_to_from_value, in case you're interested.

Btw, if I'm sending too many notifications your way, feel free to tell me to slow down for a bit here.

**Comment by ebarnard** [comment]
@jcgruenhage Sorry, I completely missed the notification for this. I'm quite busy at the moment so might take a while to get round to doing things, but very happy to get lots of notifications.

Thanks for the rebase. I seem to remember this was nearly finished. Will try and have another look tomorrow to see if I can remember what the last things to finish up were.

**Comment by jcgruenhage** [comment]
Don't worry about stuff taking a bit. Since my first version of the osquery Void extension is finished and works as expected, improving this crate further is less of a priority for me right now. Both this PR as well as the error message improvement issue will be interesting for me when I continue on that extension and use structs instead of the `Value` type, but since the MVP exists and is running smoothly, other work has taken priority for me right now.

**Comment by epilys** [comment]
@jcgruenhage could you merge this since you fixed the doc issues in your code review? If it cannot rebase without conflicts I am willing to do that. (I need this feature)

**Comment by naturecodevoid** [comment]
Is there anything stopping this PR from being merged?

**Comment by ebarnard** [comment]
@naturecodevoid Absolutely nothing, I've just been busy and forgot about it.
